name: Deploy to Minikube using GitHub Actions

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    name: build Node.js Docker Image and deploy to minikube
    steps:
      - uses: actions/checkout@v2
      - name: start minikube
        uses: medyah/setup-minikube@master
      - name: Try the cluster!
        run: kubectl get pods -A
      - name: Build image
        run: |
            export SHELL=/bin/bash
            eval $(minikube -f minikube docker-env)
            docker build -f ./Dockerfile -t devopthint/node-app:latest .
            echo -n "verifying images:"
            docker images
      - name: Deploy to minikube
        run: 
            kubectl apply -f k8s-node-app.yaml
      - name: Test service URLs
        run: |
            minikube service list
            minikube service nodejs-app --url

